### PR TITLE
Brazilian README file added

### PR DESCRIPTION
**Pull request by lnrego**
Brazilian README file added

### CODE REVIEW

**Review by loafyloaf — APPROVED** [review]
lgtm

**Comment by lnrego** [comment]
Hi @loafyloaf, is there something wrong on this pull?

**Comment by loafyloaf** [comment]
well, now it needs the latest changes from master...

**Comment by lnrego** [comment]
Well, so it would require a new translation? 

This document is the one that was required.

**Comment by lnrego** [comment]
@loafyloaf

**Pull request merged**
